name: CI
on: 
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run Flutter test and analyze
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test

  build:
    name: Build and Release
    needs: [flutter_test]
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Push and Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}